"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .filterand import FilterAnd, FilterAndTypedDict
from .filterexpression import FilterExpression, FilterExpressionTypedDict
from .filternot import FilterNot, FilterNotTypedDict
from .filteror import FilterOr, FilterOrTypedDict
from typing import Any, TYPE_CHECKING

from clay.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .aggregateselect import AggregateSelect, AggregateSelectTypedDict, Fn
    from .batchresultscomplete import (
        BatchResultsComplete,
        BatchResultsCompleteTypedDict,
    )
    from .batchresultsinprogress import (
        BatchResultsInProgress,
        BatchResultsInProgressTypedDict,
    )
    from .batchresultsprocessingfailed import (
        BatchResultsProcessingFailed,
        BatchResultsProcessingFailedError,
        BatchResultsProcessingFailedErrorTypedDict,
        BatchResultsProcessingFailedTypedDict,
    )
    from .batchresultsterminal import (
        BatchResultsTerminal,
        BatchResultsTerminalTypedDict,
        UnknownBatchResultsTerminal,
    )
    from .batchresultsvalidationfailed import (
        BatchResultsValidationFailed,
        BatchResultsValidationFailedTypedDict,
    )
    from .batchuploadurlresponse import (
        BatchUploadURLResponse,
        BatchUploadURLResponseTypedDict,
    )
    from .batchvalidationerror import (
        BatchValidationError,
        BatchValidationErrorTypedDict,
    )
    from .batchvalidationerrordetail import (
        BatchValidationErrorDetail,
        BatchValidationErrorDetailTypedDict,
    )
    from .cellempty import CellEmpty, CellEmptyTypedDict
    from .cellerror import CellError, CellErrorTypedDict
    from .cellpending import CellPending, CellPendingStatus, CellPendingTypedDict
    from .cellresult import CellResult, CellResultTypedDict, UnknownCellResult
    from .cellsuccess import CellSuccess, CellSuccessTypedDict
    from .createquerymodeop import (
        CreateQueryModeRequest,
        CreateQueryModeRequestTypedDict,
        CreateQueryModeResponse,
        CreateQueryModeResponseTypedDict,
        CreateQueryModeSourceType,
    )
    from .createsearchrequest import (
        CreateSearchRequest,
        CreateSearchRequestSourceType,
        CreateSearchRequestTypedDict,
    )
    from .createsearchresponse import (
        CreateSearchResponse,
        CreateSearchResponseTypedDict,
    )
    from .fieldmeta import FieldMeta, FieldMetaTypedDict
    from .fieldselect import FieldSelect, FieldSelectTypedDict
    from .fieldsop import FieldsRequest, FieldsRequestTypedDict, FieldsSourceType
    from .filterpredicate import (
        FilterPredicate,
        FilterPredicateTypedDict,
        Op,
        Value1,
        Value1TypedDict,
        Value2,
        Value2TypedDict,
    )
    from .getpublicapimeop import (
        GetPublicAPIMeResponse,
        GetPublicAPIMeResponseTypedDict,
        User,
        UserTypedDict,
        Workspace,
        WorkspaceTypedDict,
    )
    from .getroutinerunbatchresultsop import (
        GetRoutineRunBatchResultsRequest,
        GetRoutineRunBatchResultsRequestTypedDict,
        GetRoutineRunBatchResultsResponse,
        GetRoutineRunBatchResultsResponseTypedDict,
    )
    from .getrunresultsop import (
        GetRunResultsRequest,
        GetRunResultsRequestTypedDict,
        GetRunResultsResponse,
        GetRunResultsResponseTypedDict,
        UnknownGetRunResultsResponse,
    )
    from .nextquerymodecompanyresultsresponse import (
        NextQueryModeCompanyResultsResponse,
        NextQueryModeCompanyResultsResponseExhaustionReason,
        NextQueryModeCompanyResultsResponsePeriodQuota,
        NextQueryModeCompanyResultsResponsePeriodQuotaTypedDict,
        NextQueryModeCompanyResultsResponseTypedDict,
    )
    from .nextquerymodepeopleresultsresponse import (
        NextQueryModePeopleResultsResponse,
        NextQueryModePeopleResultsResponseExhaustionReason,
        NextQueryModePeopleResultsResponsePeriodQuota,
        NextQueryModePeopleResultsResponsePeriodQuotaTypedDict,
        NextQueryModePeopleResultsResponseTypedDict,
    )
    from .nextquerymoderesultsresponse import (
        NextQueryModeResultsResponse,
        NextQueryModeResultsResponseTypedDict,
        UnknownNextQueryModeResultsResponse,
    )
    from .nextsearchresultsbody import (
        NextSearchResultsBody,
        NextSearchResultsBodyTypedDict,
    )
    from .nextsearchresultsresponse import (
        NextSearchResultsResponse,
        NextSearchResultsResponsePeriodQuota,
        NextSearchResultsResponsePeriodQuotaTypedDict,
        NextSearchResultsResponseTypedDict,
    )
    from .publicapicompanysearchresult import (
        PublicAPICompanySearchResult,
        PublicAPICompanySearchResultTypedDict,
    )
    from .publicapimatchedexperience import (
        PublicAPIMatchedExperience,
        PublicAPIMatchedExperienceTypedDict,
    )
    from .publicapipersonsearchresult import (
        Location,
        LocationTypedDict,
        PublicAPIPersonSearchResult,
        PublicAPIPersonSearchResultTypedDict,
    )
    from .querymodereferenceop import (
        QueryModeReferenceResponse,
        QueryModeReferenceResponseTypedDict,
    )
    from .queryresponse import QueryResponse, QueryResponseTypedDict
    from .runop import RunRequest, RunRequestTypedDict
    from .runquerymodeop import RunQueryModeRequest, RunQueryModeRequestTypedDict
    from .runresultitem import (
        RunResultItem,
        RunResultItemError,
        RunResultItemErrorTypedDict,
        RunResultItemStatus,
        RunResultItemTypedDict,
    )
    from .runresultscomplete import RunResultsComplete, RunResultsCompleteTypedDict
    from .runresultsinprogress import (
        RunResultsInProgress,
        RunResultsInProgressTypedDict,
    )
    from .runroutinebatchuploadurlop import (
        RunRoutineBatchUploadURLRequest,
        RunRoutineBatchUploadURLRequestTypedDict,
    )
    from .runroutineop import (
        RunRoutineRequestRequest,
        RunRoutineRequestRequestTypedDict,
    )
    from .runroutinerequest import (
        Item,
        ItemTypedDict,
        RunRoutineRequest,
        RunRoutineRequestTypedDict,
    )
    from .runroutineresponse import RunRoutineResponse, RunRoutineResponseTypedDict
    from .searchcreateexample import (
        Request,
        RequestTypedDict,
        SearchCreateExample,
        SearchCreateExampleSourceType,
        SearchCreateExampleTypedDict,
    )
    from .searchfieldsguidance import (
        SearchFieldsGuidance,
        SearchFieldsGuidanceTypedDict,
    )
    from .searchfieldsresponse import (
        SearchFieldsResponse,
        SearchFieldsResponseSourceType,
        SearchFieldsResponseTypedDict,
    )
    from .searchfilterfield import SearchFilterField, SearchFilterFieldTypedDict
    from .searchguidanceitem import SearchGuidanceItem, SearchGuidanceItemTypedDict
    from .security import Security, SecurityTypedDict
    from .startbatchrequest import StartBatchRequest, StartBatchRequestTypedDict
    from .startbatchresponse import StartBatchResponse, StartBatchResponseTypedDict
    from .startroutinerunbatchop import (
        StartRoutineRunBatchRequest,
        StartRoutineRunBatchRequestTypedDict,
    )
    from .structuredquery import (
        Direction,
        FieldMode,
        Join,
        JoinTypedDict,
        On,
        OnTypedDict,
        OrderBy,
        OrderByTypedDict,
        Select,
        SelectTypedDict,
        StructuredQuery,
        StructuredQueryTypedDict,
        Table,
        TableTypedDict,
        Type,
    )
    from .structuredqueryrequest import (
        StructuredQueryRequest,
        StructuredQueryRequestTypedDict,
    )  # Pydantic models with forward references
FilterAnd.model_rebuild()
FilterOr.model_rebuild()
FilterNot.model_rebuild()


__all__ = [
    "AggregateSelect",
    "AggregateSelectTypedDict",
    "BatchResultsComplete",
    "BatchResultsCompleteTypedDict",
    "BatchResultsInProgress",
    "BatchResultsInProgressTypedDict",
    "BatchResultsProcessingFailed",
    "BatchResultsProcessingFailedError",
    "BatchResultsProcessingFailedErrorTypedDict",
    "BatchResultsProcessingFailedTypedDict",
    "BatchResultsTerminal",
    "BatchResultsTerminalTypedDict",
    "BatchResultsValidationFailed",
    "BatchResultsValidationFailedTypedDict",
    "BatchUploadURLResponse",
    "BatchUploadURLResponseTypedDict",
    "BatchValidationError",
    "BatchValidationErrorDetail",
    "BatchValidationErrorDetailTypedDict",
    "BatchValidationErrorTypedDict",
    "CellEmpty",
    "CellEmptyTypedDict",
    "CellError",
    "CellErrorTypedDict",
    "CellPending",
    "CellPendingStatus",
    "CellPendingTypedDict",
    "CellResult",
    "CellResultTypedDict",
    "CellSuccess",
    "CellSuccessTypedDict",
    "CreateQueryModeRequest",
    "CreateQueryModeRequestTypedDict",
    "CreateQueryModeResponse",
    "CreateQueryModeResponseTypedDict",
    "CreateQueryModeSourceType",
    "CreateSearchRequest",
    "CreateSearchRequestSourceType",
    "CreateSearchRequestTypedDict",
    "CreateSearchResponse",
    "CreateSearchResponseTypedDict",
    "Direction",
    "FieldMeta",
    "FieldMetaTypedDict",
    "FieldMode",
    "FieldSelect",
    "FieldSelectTypedDict",
    "FieldsRequest",
    "FieldsRequestTypedDict",
    "FieldsSourceType",
    "FilterAnd",
    "FilterAndTypedDict",
    "FilterExpression",
    "FilterExpressionTypedDict",
    "FilterNot",
    "FilterNotTypedDict",
    "FilterOr",
    "FilterOrTypedDict",
    "FilterPredicate",
    "FilterPredicateTypedDict",
    "Fn",
    "GetPublicAPIMeResponse",
    "GetPublicAPIMeResponseTypedDict",
    "GetRoutineRunBatchResultsRequest",
    "GetRoutineRunBatchResultsRequestTypedDict",
    "GetRoutineRunBatchResultsResponse",
    "GetRoutineRunBatchResultsResponseTypedDict",
    "GetRunResultsRequest",
    "GetRunResultsRequestTypedDict",
    "GetRunResultsResponse",
    "GetRunResultsResponseTypedDict",
    "Item",
    "ItemTypedDict",
    "Join",
    "JoinTypedDict",
    "Location",
    "LocationTypedDict",
    "NextQueryModeCompanyResultsResponse",
    "NextQueryModeCompanyResultsResponseExhaustionReason",
    "NextQueryModeCompanyResultsResponsePeriodQuota",
    "NextQueryModeCompanyResultsResponsePeriodQuotaTypedDict",
    "NextQueryModeCompanyResultsResponseTypedDict",
    "NextQueryModePeopleResultsResponse",
    "NextQueryModePeopleResultsResponseExhaustionReason",
    "NextQueryModePeopleResultsResponsePeriodQuota",
    "NextQueryModePeopleResultsResponsePeriodQuotaTypedDict",
    "NextQueryModePeopleResultsResponseTypedDict",
    "NextQueryModeResultsResponse",
    "NextQueryModeResultsResponseTypedDict",
    "NextSearchResultsBody",
    "NextSearchResultsBodyTypedDict",
    "NextSearchResultsResponse",
    "NextSearchResultsResponsePeriodQuota",
    "NextSearchResultsResponsePeriodQuotaTypedDict",
    "NextSearchResultsResponseTypedDict",
    "On",
    "OnTypedDict",
    "Op",
    "OrderBy",
    "OrderByTypedDict",
    "PublicAPICompanySearchResult",
    "PublicAPICompanySearchResultTypedDict",
    "PublicAPIMatchedExperience",
    "PublicAPIMatchedExperienceTypedDict",
    "PublicAPIPersonSearchResult",
    "PublicAPIPersonSearchResultTypedDict",
    "QueryModeReferenceResponse",
    "QueryModeReferenceResponseTypedDict",
    "QueryResponse",
    "QueryResponseTypedDict",
    "Request",
    "RequestTypedDict",
    "RunQueryModeRequest",
    "RunQueryModeRequestTypedDict",
    "RunRequest",
    "RunRequestTypedDict",
    "RunResultItem",
    "RunResultItemError",
    "RunResultItemErrorTypedDict",
    "RunResultItemStatus",
    "RunResultItemTypedDict",
    "RunResultsComplete",
    "RunResultsCompleteTypedDict",
    "RunResultsInProgress",
    "RunResultsInProgressTypedDict",
    "RunRoutineBatchUploadURLRequest",
    "RunRoutineBatchUploadURLRequestTypedDict",
    "RunRoutineRequest",
    "RunRoutineRequestRequest",
    "RunRoutineRequestRequestTypedDict",
    "RunRoutineRequestTypedDict",
    "RunRoutineResponse",
    "RunRoutineResponseTypedDict",
    "SearchCreateExample",
    "SearchCreateExampleSourceType",
    "SearchCreateExampleTypedDict",
    "SearchFieldsGuidance",
    "SearchFieldsGuidanceTypedDict",
    "SearchFieldsResponse",
    "SearchFieldsResponseSourceType",
    "SearchFieldsResponseTypedDict",
    "SearchFilterField",
    "SearchFilterFieldTypedDict",
    "SearchGuidanceItem",
    "SearchGuidanceItemTypedDict",
    "Security",
    "SecurityTypedDict",
    "Select",
    "SelectTypedDict",
    "StartBatchRequest",
    "StartBatchRequestTypedDict",
    "StartBatchResponse",
    "StartBatchResponseTypedDict",
    "StartRoutineRunBatchRequest",
    "StartRoutineRunBatchRequestTypedDict",
    "StructuredQuery",
    "StructuredQueryRequest",
    "StructuredQueryRequestTypedDict",
    "StructuredQueryTypedDict",
    "Table",
    "TableTypedDict",
    "Type",
    "UnknownBatchResultsTerminal",
    "UnknownCellResult",
    "UnknownGetRunResultsResponse",
    "UnknownNextQueryModeResultsResponse",
    "User",
    "UserTypedDict",
    "Value1",
    "Value1TypedDict",
    "Value2",
    "Value2TypedDict",
    "Workspace",
    "WorkspaceTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AggregateSelect": ".aggregateselect",
    "AggregateSelectTypedDict": ".aggregateselect",
    "Fn": ".aggregateselect",
    "BatchResultsComplete": ".batchresultscomplete",
    "BatchResultsCompleteTypedDict": ".batchresultscomplete",
    "BatchResultsInProgress": ".batchresultsinprogress",
    "BatchResultsInProgressTypedDict": ".batchresultsinprogress",
    "BatchResultsProcessingFailed": ".batchresultsprocessingfailed",
    "BatchResultsProcessingFailedError": ".batchresultsprocessingfailed",
    "BatchResultsProcessingFailedErrorTypedDict": ".batchresultsprocessingfailed",
    "BatchResultsProcessingFailedTypedDict": ".batchresultsprocessingfailed",
    "BatchResultsTerminal": ".batchresultsterminal",
    "BatchResultsTerminalTypedDict": ".batchresultsterminal",
    "UnknownBatchResultsTerminal": ".batchresultsterminal",
    "BatchResultsValidationFailed": ".batchresultsvalidationfailed",
    "BatchResultsValidationFailedTypedDict": ".batchresultsvalidationfailed",
    "BatchUploadURLResponse": ".batchuploadurlresponse",
    "BatchUploadURLResponseTypedDict": ".batchuploadurlresponse",
    "BatchValidationError": ".batchvalidationerror",
    "BatchValidationErrorTypedDict": ".batchvalidationerror",
    "BatchValidationErrorDetail": ".batchvalidationerrordetail",
    "BatchValidationErrorDetailTypedDict": ".batchvalidationerrordetail",
    "CellEmpty": ".cellempty",
    "CellEmptyTypedDict": ".cellempty",
    "CellError": ".cellerror",
    "CellErrorTypedDict": ".cellerror",
    "CellPending": ".cellpending",
    "CellPendingStatus": ".cellpending",
    "CellPendingTypedDict": ".cellpending",
    "CellResult": ".cellresult",
    "CellResultTypedDict": ".cellresult",
    "UnknownCellResult": ".cellresult",
    "CellSuccess": ".cellsuccess",
    "CellSuccessTypedDict": ".cellsuccess",
    "CreateQueryModeRequest": ".createquerymodeop",
    "CreateQueryModeRequestTypedDict": ".createquerymodeop",
    "CreateQueryModeResponse": ".createquerymodeop",
    "CreateQueryModeResponseTypedDict": ".createquerymodeop",
    "CreateQueryModeSourceType": ".createquerymodeop",
    "CreateSearchRequest": ".createsearchrequest",
    "CreateSearchRequestSourceType": ".createsearchrequest",
    "CreateSearchRequestTypedDict": ".createsearchrequest",
    "CreateSearchResponse": ".createsearchresponse",
    "CreateSearchResponseTypedDict": ".createsearchresponse",
    "FieldMeta": ".fieldmeta",
    "FieldMetaTypedDict": ".fieldmeta",
    "FieldSelect": ".fieldselect",
    "FieldSelectTypedDict": ".fieldselect",
    "FieldsRequest": ".fieldsop",
    "FieldsRequestTypedDict": ".fieldsop",
    "FieldsSourceType": ".fieldsop",
    "FilterPredicate": ".filterpredicate",
    "FilterPredicateTypedDict": ".filterpredicate",
    "Op": ".filterpredicate",
    "Value1": ".filterpredicate",
    "Value1TypedDict": ".filterpredicate",
    "Value2": ".filterpredicate",
    "Value2TypedDict": ".filterpredicate",
    "GetPublicAPIMeResponse": ".getpublicapimeop",
    "GetPublicAPIMeResponseTypedDict": ".getpublicapimeop",
    "User": ".getpublicapimeop",
    "UserTypedDict": ".getpublicapimeop",
    "Workspace": ".getpublicapimeop",
    "WorkspaceTypedDict": ".getpublicapimeop",
    "GetRoutineRunBatchResultsRequest": ".getroutinerunbatchresultsop",
    "GetRoutineRunBatchResultsRequestTypedDict": ".getroutinerunbatchresultsop",
    "GetRoutineRunBatchResultsResponse": ".getroutinerunbatchresultsop",
    "GetRoutineRunBatchResultsResponseTypedDict": ".getroutinerunbatchresultsop",
    "GetRunResultsRequest": ".getrunresultsop",
    "GetRunResultsRequestTypedDict": ".getrunresultsop",
    "GetRunResultsResponse": ".getrunresultsop",
    "GetRunResultsResponseTypedDict": ".getrunresultsop",
    "UnknownGetRunResultsResponse": ".getrunresultsop",
    "NextQueryModeCompanyResultsResponse": ".nextquerymodecompanyresultsresponse",
    "NextQueryModeCompanyResultsResponseExhaustionReason": ".nextquerymodecompanyresultsresponse",
    "NextQueryModeCompanyResultsResponsePeriodQuota": ".nextquerymodecompanyresultsresponse",
    "NextQueryModeCompanyResultsResponsePeriodQuotaTypedDict": ".nextquerymodecompanyresultsresponse",
    "NextQueryModeCompanyResultsResponseTypedDict": ".nextquerymodecompanyresultsresponse",
    "NextQueryModePeopleResultsResponse": ".nextquerymodepeopleresultsresponse",
    "NextQueryModePeopleResultsResponseExhaustionReason": ".nextquerymodepeopleresultsresponse",
    "NextQueryModePeopleResultsResponsePeriodQuota": ".nextquerymodepeopleresultsresponse",
    "NextQueryModePeopleResultsResponsePeriodQuotaTypedDict": ".nextquerymodepeopleresultsresponse",
    "NextQueryModePeopleResultsResponseTypedDict": ".nextquerymodepeopleresultsresponse",
    "NextQueryModeResultsResponse": ".nextquerymoderesultsresponse",
    "NextQueryModeResultsResponseTypedDict": ".nextquerymoderesultsresponse",
    "UnknownNextQueryModeResultsResponse": ".nextquerymoderesultsresponse",
    "NextSearchResultsBody": ".nextsearchresultsbody",
    "NextSearchResultsBodyTypedDict": ".nextsearchresultsbody",
    "NextSearchResultsResponse": ".nextsearchresultsresponse",
    "NextSearchResultsResponsePeriodQuota": ".nextsearchresultsresponse",
    "NextSearchResultsResponsePeriodQuotaTypedDict": ".nextsearchresultsresponse",
    "NextSearchResultsResponseTypedDict": ".nextsearchresultsresponse",
    "PublicAPICompanySearchResult": ".publicapicompanysearchresult",
    "PublicAPICompanySearchResultTypedDict": ".publicapicompanysearchresult",
    "PublicAPIMatchedExperience": ".publicapimatchedexperience",
    "PublicAPIMatchedExperienceTypedDict": ".publicapimatchedexperience",
    "Location": ".publicapipersonsearchresult",
    "LocationTypedDict": ".publicapipersonsearchresult",
    "PublicAPIPersonSearchResult": ".publicapipersonsearchresult",
    "PublicAPIPersonSearchResultTypedDict": ".publicapipersonsearchresult",
    "QueryModeReferenceResponse": ".querymodereferenceop",
    "QueryModeReferenceResponseTypedDict": ".querymodereferenceop",
    "QueryResponse": ".queryresponse",
    "QueryResponseTypedDict": ".queryresponse",
    "RunRequest": ".runop",
    "RunRequestTypedDict": ".runop",
    "RunQueryModeRequest": ".runquerymodeop",
    "RunQueryModeRequestTypedDict": ".runquerymodeop",
    "RunResultItem": ".runresultitem",
    "RunResultItemError": ".runresultitem",
    "RunResultItemErrorTypedDict": ".runresultitem",
    "RunResultItemStatus": ".runresultitem",
    "RunResultItemTypedDict": ".runresultitem",
    "RunResultsComplete": ".runresultscomplete",
    "RunResultsCompleteTypedDict": ".runresultscomplete",
    "RunResultsInProgress": ".runresultsinprogress",
    "RunResultsInProgressTypedDict": ".runresultsinprogress",
    "RunRoutineBatchUploadURLRequest": ".runroutinebatchuploadurlop",
    "RunRoutineBatchUploadURLRequestTypedDict": ".runroutinebatchuploadurlop",
    "RunRoutineRequestRequest": ".runroutineop",
    "RunRoutineRequestRequestTypedDict": ".runroutineop",
    "Item": ".runroutinerequest",
    "ItemTypedDict": ".runroutinerequest",
    "RunRoutineRequest": ".runroutinerequest",
    "RunRoutineRequestTypedDict": ".runroutinerequest",
    "RunRoutineResponse": ".runroutineresponse",
    "RunRoutineResponseTypedDict": ".runroutineresponse",
    "Request": ".searchcreateexample",
    "RequestTypedDict": ".searchcreateexample",
    "SearchCreateExample": ".searchcreateexample",
    "SearchCreateExampleSourceType": ".searchcreateexample",
    "SearchCreateExampleTypedDict": ".searchcreateexample",
    "SearchFieldsGuidance": ".searchfieldsguidance",
    "SearchFieldsGuidanceTypedDict": ".searchfieldsguidance",
    "SearchFieldsResponse": ".searchfieldsresponse",
    "SearchFieldsResponseSourceType": ".searchfieldsresponse",
    "SearchFieldsResponseTypedDict": ".searchfieldsresponse",
    "SearchFilterField": ".searchfilterfield",
    "SearchFilterFieldTypedDict": ".searchfilterfield",
    "SearchGuidanceItem": ".searchguidanceitem",
    "SearchGuidanceItemTypedDict": ".searchguidanceitem",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "StartBatchRequest": ".startbatchrequest",
    "StartBatchRequestTypedDict": ".startbatchrequest",
    "StartBatchResponse": ".startbatchresponse",
    "StartBatchResponseTypedDict": ".startbatchresponse",
    "StartRoutineRunBatchRequest": ".startroutinerunbatchop",
    "StartRoutineRunBatchRequestTypedDict": ".startroutinerunbatchop",
    "Direction": ".structuredquery",
    "FieldMode": ".structuredquery",
    "Join": ".structuredquery",
    "JoinTypedDict": ".structuredquery",
    "On": ".structuredquery",
    "OnTypedDict": ".structuredquery",
    "OrderBy": ".structuredquery",
    "OrderByTypedDict": ".structuredquery",
    "Select": ".structuredquery",
    "SelectTypedDict": ".structuredquery",
    "StructuredQuery": ".structuredquery",
    "StructuredQueryTypedDict": ".structuredquery",
    "Table": ".structuredquery",
    "TableTypedDict": ".structuredquery",
    "Type": ".structuredquery",
    "StructuredQueryRequest": ".structuredqueryrequest",
    "StructuredQueryRequestTypedDict": ".structuredqueryrequest",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
