"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batchresultscomplete import BatchResultsComplete, BatchResultsCompleteTypedDict
from .batchresultsvalidationfailed import (
    BatchResultsValidationFailed,
    BatchResultsValidationFailedTypedDict,
)
from clay.types import BaseModel
from clay.utils.unions import parse_open_union
from functools import partial
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


BatchResultsTerminalTypedDict = TypeAliasType(
    "BatchResultsTerminalTypedDict",
    Union[BatchResultsValidationFailedTypedDict, BatchResultsCompleteTypedDict],
)


class UnknownBatchResultsTerminal(BaseModel):
    r"""A BatchResultsTerminal variant the SDK doesn't recognize. Preserves the raw payload."""

    status: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_BATCH_RESULTS_TERMINAL_VARIANTS: dict[str, Any] = {
    "validation_failed": BatchResultsValidationFailed,
    "complete": BatchResultsComplete,
}


BatchResultsTerminal = Annotated[
    Union[
        BatchResultsValidationFailed, BatchResultsComplete, UnknownBatchResultsTerminal
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="status",
            variants=_BATCH_RESULTS_TERMINAL_VARIANTS,
            unknown_cls=UnknownBatchResultsTerminal,
            union_name="BatchResultsTerminal",
        )
    ),
]
