"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from clay.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class BatchResultsProcessingFailedErrorTypedDict(TypedDict):
    message: str


class BatchResultsProcessingFailedError(BaseModel):
    message: str


class BatchResultsProcessingFailedTypedDict(TypedDict):
    error: BatchResultsProcessingFailedErrorTypedDict
    routine_run_id: str
    status: Literal["processing_failed"]


class BatchResultsProcessingFailed(BaseModel):
    error: BatchResultsProcessingFailedError

    routine_run_id: str

    status: Annotated[
        Annotated[
            Literal["processing_failed"],
            AfterValidator(validate_const("processing_failed")),
        ],
        pydantic.Field(alias="status"),
    ] = "processing_failed"


try:
    BatchResultsProcessingFailed.model_rebuild()
except NameError:
    pass
