"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from clay.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class BatchResultsCompleteTypedDict(TypedDict):
    finished: float
    result_url: str
    routine_run_id: str
    total: float
    status: Literal["complete"]


class BatchResultsComplete(BaseModel):
    finished: float

    result_url: str

    routine_run_id: str

    total: float

    status: Annotated[
        Annotated[Literal["complete"], AfterValidator(validate_const("complete"))],
        pydantic.Field(alias="status"),
    ] = "complete"


try:
    BatchResultsComplete.model_rebuild()
except NameError:
    pass
