"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from typing_extensions import TypedDict


class BatchValidationErrorDetailTypedDict(TypedDict):
    field: str
    line_number: float
    message: str


class BatchValidationErrorDetail(BaseModel):
    field: str

    line_number: float

    message: str
