"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batchvalidationerrordetail import (
    BatchValidationErrorDetail,
    BatchValidationErrorDetailTypedDict,
)
from clay.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class BatchValidationErrorTypedDict(TypedDict):
    details: List[BatchValidationErrorDetailTypedDict]
    message: str
    total_invalid_rows: float


class BatchValidationError(BaseModel):
    details: List[BatchValidationErrorDetail]

    message: str

    total_invalid_rows: float
