"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from typing_extensions import TypedDict


class BatchUploadURLResponseTypedDict(TypedDict):
    file_id: str
    upload_url: str


class BatchUploadURLResponse(BaseModel):
    file_id: str

    upload_url: str
