"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batchvalidationerror import BatchValidationError, BatchValidationErrorTypedDict
from clay.types import BaseModel
from clay.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class BatchResultsValidationFailedTypedDict(TypedDict):
    error: BatchValidationErrorTypedDict
    routine_run_id: str
    status: Literal["validation_failed"]


class BatchResultsValidationFailed(BaseModel):
    error: BatchValidationError

    routine_run_id: str

    status: Annotated[
        Annotated[
            Literal["validation_failed"],
            AfterValidator(validate_const("validation_failed")),
        ],
        pydantic.Field(alias="status"),
    ] = "validation_failed"


try:
    BatchResultsValidationFailed.model_rebuild()
except NameError:
    pass
