"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, Nullable, UNSET_SENTINEL
from clay.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CellSuccessTypedDict(TypedDict):
    fields: Nullable[Dict[str, Any]]
    is_stale: Literal[True]
    status: Literal["success"]
    value: NotRequired[Any]


class CellSuccess(BaseModel):
    fields: Nullable[Dict[str, Any]]

    is_stale: Annotated[
        Annotated[Optional[Literal[True]], AfterValidator(validate_const(True))],
        pydantic.Field(alias="is_stale"),
    ] = True

    status: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"

    value: Optional[Any] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["is_stale", "value"])
        nullable_fields = set(["fields"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CellSuccess.model_rebuild()
except NameError:
    pass
