"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


CellPendingStatus = Union[
    Literal[
        "running",
        "queued",
        "retry",
        "rate_limited",
        "awaiting_callback",
    ],
    UnrecognizedStr,
]


class CellPendingTypedDict(TypedDict):
    status: CellPendingStatus


class CellPending(BaseModel):
    status: CellPendingStatus
