"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UNSET_SENTINEL
from clay.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CellErrorTypedDict(TypedDict):
    error: NotRequired[str]
    status: Literal["error"]


class CellError(BaseModel):
    error: Optional[str] = None

    status: Annotated[
        Annotated[Literal["error"], AfterValidator(validate_const("error"))],
        pydantic.Field(alias="status"),
    ] = "error"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CellError.model_rebuild()
except NameError:
    pass
