"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cellempty import CellEmpty, CellEmptyTypedDict
from .cellerror import CellError, CellErrorTypedDict
from .cellpending import CellPending, CellPendingTypedDict
from .cellsuccess import CellSuccess, CellSuccessTypedDict
from clay.types import BaseModel
from clay.utils.unions import parse_open_union
from functools import partial
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


CellResultTypedDict = TypeAliasType(
    "CellResultTypedDict",
    Union[
        CellPendingTypedDict,
        CellEmptyTypedDict,
        CellErrorTypedDict,
        CellSuccessTypedDict,
    ],
)


class UnknownCellResult(BaseModel):
    r"""A CellResult variant the SDK doesn't recognize. Preserves the raw payload."""

    status: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_CELL_RESULT_VARIANTS: dict[str, Any] = {
    "success": CellSuccess,
    "error": CellError,
    "running": CellPending,
    "queued": CellPending,
    "retry": CellPending,
    "rate_limited": CellPending,
    "awaiting_callback": CellPending,
    "empty": CellEmpty,
}


CellResult = Annotated[
    Union[
        CellSuccess,
        CellError,
        CellPending,
        CellPending,
        CellPending,
        CellPending,
        CellPending,
        CellEmpty,
        UnknownCellResult,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="status",
            variants=_CELL_RESULT_VARIANTS,
            unknown_cls=UnknownCellResult,
            union_name="CellResult",
        )
    ),
]
