"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from clay.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class CellEmptyTypedDict(TypedDict):
    status: Literal["empty"]


class CellEmpty(BaseModel):
    status: Annotated[
        Annotated[Literal["empty"], AfterValidator(validate_const("empty"))],
        pydantic.Field(alias="status"),
    ] = "empty"


try:
    CellEmpty.model_rebuild()
except NameError:
    pass
