"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


class CreateQueryModeRequestTypedDict(TypedDict):
    r"""Body"""

    query: str


class CreateQueryModeRequest(BaseModel):
    r"""Body"""

    query: str


CreateQueryModeSourceType = Union[
    Literal[
        "people",
        "companies",
    ],
    UnrecognizedStr,
]


class CreateQueryModeResponseTypedDict(TypedDict):
    r"""200"""

    search_id: str
    source_type: CreateQueryModeSourceType


class CreateQueryModeResponse(BaseModel):
    r"""200"""

    search_id: str

    source_type: CreateQueryModeSourceType
