"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from typing_extensions import TypedDict


class CreateSearchResponseTypedDict(TypedDict):
    search_id: str


class CreateSearchResponse(BaseModel):
    search_id: str
