"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from typing import Any, Dict, Literal
from typing_extensions import TypedDict


CreateSearchRequestSourceType = Literal[
    "people",
    "companies",
]


class CreateSearchRequestTypedDict(TypedDict):
    filters: Dict[str, Any]
    source_type: CreateSearchRequestSourceType


class CreateSearchRequest(BaseModel):
    filters: Dict[str, Any]

    source_type: CreateSearchRequestSourceType
