"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from typing_extensions import TypedDict


class FieldMetaTypedDict(TypedDict):
    id: str
    name: str
    type: str


class FieldMeta(BaseModel):
    id: str

    name: str

    type: str
