"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from clay.utils import FieldMetadata, QueryParamMetadata
from typing import Literal
from typing_extensions import Annotated, TypedDict


FieldsSourceType = Literal[
    "people",
    "companies",
]


class FieldsRequestTypedDict(TypedDict):
    source_type: FieldsSourceType


class FieldsRequest(BaseModel):
    source_type: Annotated[
        FieldsSourceType,
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
