"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FieldSelectTypedDict(TypedDict):
    field: str
    as_: NotRequired[str]
    path: NotRequired[List[str]]
    table: NotRequired[str]


class FieldSelect(BaseModel):
    field: str

    as_: Annotated[Optional[str], pydantic.Field(alias="as")] = None

    path: Optional[List[str]] = None

    table: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["as", "path", "table"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FieldSelect.model_rebuild()
except NameError:
    pass
