"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


Op = Literal[
    "=",
    "!=",
    ">",
    ">=",
    "<",
    "<=",
    "contains",
    "not_contains",
    "starts_with",
    "ends_with",
    "in",
    "not_in",
    "is_empty",
    "is_not_empty",
]


Value1TypedDict = TypeAliasType("Value1TypedDict", Union[str, float])


Value1 = TypeAliasType("Value1", Union[str, float])


Value2TypedDict = TypeAliasType(
    "Value2TypedDict", Union[str, float, bool, List[Value1TypedDict]]
)


Value2 = TypeAliasType("Value2", Union[str, float, bool, List[Value1]])


class FilterPredicateTypedDict(TypedDict):
    field: str
    op: Op
    path: NotRequired[List[str]]
    value: NotRequired[Value2TypedDict]


class FilterPredicate(BaseModel):
    field: str

    op: Op

    path: Optional[List[str]] = None

    value: Optional[Value2] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["path", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
