"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
import pydantic
from typing import TYPE_CHECKING
from typing_extensions import Annotated, TypedDict

if TYPE_CHECKING:
    from .filterexpression import FilterExpression, FilterExpressionTypedDict


class FilterNotTypedDict(TypedDict):
    not_: "FilterExpressionTypedDict"


class FilterNot(BaseModel):
    not_: Annotated["FilterExpression", pydantic.Field(alias="not")]


try:
    FilterNot.model_rebuild()
except NameError:
    pass
