"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filterpredicate import FilterPredicate, FilterPredicateTypedDict
from typing import TYPE_CHECKING, Union
from typing_extensions import TypeAliasType

if TYPE_CHECKING:
    from .filterand import FilterAnd, FilterAndTypedDict
    from .filternot import FilterNot, FilterNotTypedDict
    from .filteror import FilterOr, FilterOrTypedDict


FilterExpressionTypedDict = TypeAliasType(
    "FilterExpressionTypedDict",
    Union[
        "FilterAndTypedDict",
        "FilterOrTypedDict",
        "FilterNotTypedDict",
        FilterPredicateTypedDict,
    ],
)


FilterExpression = TypeAliasType(
    "FilterExpression", Union["FilterAnd", "FilterOr", "FilterNot", FilterPredicate]
)
