"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
import pydantic
from typing import List, TYPE_CHECKING
from typing_extensions import Annotated, TypedDict

if TYPE_CHECKING:
    from .filterexpression import FilterExpression, FilterExpressionTypedDict


class FilterOrTypedDict(TypedDict):
    or_: List["FilterExpressionTypedDict"]


class FilterOr(BaseModel):
    or_: Annotated[List["FilterExpression"], pydantic.Field(alias="or")]


try:
    FilterOr.model_rebuild()
except NameError:
    pass
