"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class UserTypedDict(TypedDict):
    id: str
    name: Nullable[str]


class User(BaseModel):
    id: str

    name: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class WorkspaceTypedDict(TypedDict):
    id: str


class Workspace(BaseModel):
    id: str


class GetPublicAPIMeResponseTypedDict(TypedDict):
    r"""200"""

    user: UserTypedDict
    workspace: WorkspaceTypedDict


class GetPublicAPIMeResponse(BaseModel):
    r"""200"""

    user: User

    workspace: Workspace
