"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .runresultscomplete import RunResultsComplete, RunResultsCompleteTypedDict
from .runresultsinprogress import RunResultsInProgress, RunResultsInProgressTypedDict
from clay.types import BaseModel, UNSET_SENTINEL
from clay.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from clay.utils.unions import parse_open_union
from functools import partial
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetRunResultsRequestTypedDict(TypedDict):
    routine_run_id: str
    cursor: NotRequired[str]
    limit: NotRequired[int]


class GetRunResultsRequest(BaseModel):
    routine_run_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cursor", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetRunResultsResponseTypedDict = TypeAliasType(
    "GetRunResultsResponseTypedDict",
    Union[RunResultsInProgressTypedDict, RunResultsCompleteTypedDict],
)


class UnknownGetRunResultsResponse(BaseModel):
    r"""A GetRunResultsResponse variant the SDK doesn't recognize. Preserves the raw payload."""

    status: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_GET_RUN_RESULTS_RESPONSE_VARIANTS: dict[str, Any] = {
    "complete": RunResultsComplete,
    "in_progress": RunResultsInProgress,
}


GetRunResultsResponse = Annotated[
    Union[RunResultsComplete, RunResultsInProgress, UnknownGetRunResultsResponse],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="status",
            variants=_GET_RUN_RESULTS_RESPONSE_VARIANTS,
            unknown_cls=UnknownGetRunResultsResponse,
            union_name="GetRunResultsResponse",
        )
    ),
]
