"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batchresultsinprogress import (
    BatchResultsInProgress,
    BatchResultsInProgressTypedDict,
)
from .batchresultsterminal import BatchResultsTerminal, BatchResultsTerminalTypedDict
from clay.types import BaseModel
from clay.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetRoutineRunBatchResultsRequestTypedDict(TypedDict):
    routine_run_id: str


class GetRoutineRunBatchResultsRequest(BaseModel):
    routine_run_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetRoutineRunBatchResultsResponseTypedDict = TypeAliasType(
    "GetRoutineRunBatchResultsResponseTypedDict",
    Union[BatchResultsInProgressTypedDict, BatchResultsTerminalTypedDict],
)


GetRoutineRunBatchResultsResponse = TypeAliasType(
    "GetRoutineRunBatchResultsResponse",
    Union[BatchResultsInProgress, BatchResultsTerminal],
)
