"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class NextSearchResultsResponsePeriodQuotaTypedDict(TypedDict):
    limit: float
    remaining: float
    resets_at: str
    used: float


class NextSearchResultsResponsePeriodQuota(BaseModel):
    limit: float

    remaining: float

    resets_at: str

    used: float


class NextSearchResultsResponseTypedDict(TypedDict):
    data: List[Dict[str, Any]]
    has_more: bool
    period_quota: NotRequired[NextSearchResultsResponsePeriodQuotaTypedDict]


class NextSearchResultsResponse(BaseModel):
    data: List[Dict[str, Any]]

    has_more: bool

    period_quota: Optional[NextSearchResultsResponsePeriodQuota] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["period_quota"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
