"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .publicapipersonsearchresult import (
    PublicAPIPersonSearchResult,
    PublicAPIPersonSearchResultTypedDict,
)
from clay.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from clay.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


NextQueryModePeopleResultsResponseExhaustionReason = Union[
    Literal[
        "query_limit",
        "no_more_results",
    ],
    UnrecognizedStr,
]


class NextQueryModePeopleResultsResponsePeriodQuotaTypedDict(TypedDict):
    limit: float
    remaining: float
    resets_at: str
    used: float


class NextQueryModePeopleResultsResponsePeriodQuota(BaseModel):
    limit: float

    remaining: float

    resets_at: str

    used: float


class NextQueryModePeopleResultsResponseTypedDict(TypedDict):
    data: List[PublicAPIPersonSearchResultTypedDict]
    has_more: bool
    exhaustion_reason: NotRequired[NextQueryModePeopleResultsResponseExhaustionReason]
    period_quota: NotRequired[NextQueryModePeopleResultsResponsePeriodQuotaTypedDict]
    source_type: Literal["people"]


class NextQueryModePeopleResultsResponse(BaseModel):
    data: List[PublicAPIPersonSearchResult]

    has_more: bool

    exhaustion_reason: Optional[NextQueryModePeopleResultsResponseExhaustionReason] = (
        None
    )

    period_quota: Optional[NextQueryModePeopleResultsResponsePeriodQuota] = None

    source_type: Annotated[
        Annotated[Literal["people"], AfterValidator(validate_const("people"))],
        pydantic.Field(alias="source_type"),
    ] = "people"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["exhaustion_reason", "period_quota"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    NextQueryModePeopleResultsResponse.model_rebuild()
except NameError:
    pass
