"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .publicapicompanysearchresult import (
    PublicAPICompanySearchResult,
    PublicAPICompanySearchResultTypedDict,
)
from clay.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from clay.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


NextQueryModeCompanyResultsResponseExhaustionReason = Union[
    Literal[
        "query_limit",
        "no_more_results",
    ],
    UnrecognizedStr,
]


class NextQueryModeCompanyResultsResponsePeriodQuotaTypedDict(TypedDict):
    limit: float
    remaining: float
    resets_at: str
    used: float


class NextQueryModeCompanyResultsResponsePeriodQuota(BaseModel):
    limit: float

    remaining: float

    resets_at: str

    used: float


class NextQueryModeCompanyResultsResponseTypedDict(TypedDict):
    data: List[PublicAPICompanySearchResultTypedDict]
    has_more: bool
    exhaustion_reason: NotRequired[NextQueryModeCompanyResultsResponseExhaustionReason]
    period_quota: NotRequired[NextQueryModeCompanyResultsResponsePeriodQuotaTypedDict]
    source_type: Literal["companies"]


class NextQueryModeCompanyResultsResponse(BaseModel):
    data: List[PublicAPICompanySearchResult]

    has_more: bool

    exhaustion_reason: Optional[NextQueryModeCompanyResultsResponseExhaustionReason] = (
        None
    )

    period_quota: Optional[NextQueryModeCompanyResultsResponsePeriodQuota] = None

    source_type: Annotated[
        Annotated[Literal["companies"], AfterValidator(validate_const("companies"))],
        pydantic.Field(alias="source_type"),
    ] = "companies"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["exhaustion_reason", "period_quota"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    NextQueryModeCompanyResultsResponse.model_rebuild()
except NameError:
    pass
