"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from typing import Any, Dict, List
from typing_extensions import TypedDict


class NextSearchResultsResponseTypedDict(TypedDict):
    data: List[Dict[str, Any]]
    has_more: bool


class NextSearchResultsResponse(BaseModel):
    data: List[Dict[str, Any]]

    has_more: bool
