"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .nextquerymodecompanyresultsresponse import (
    NextQueryModeCompanyResultsResponse,
    NextQueryModeCompanyResultsResponseTypedDict,
)
from .nextquerymodepeopleresultsresponse import (
    NextQueryModePeopleResultsResponse,
    NextQueryModePeopleResultsResponseTypedDict,
)
from clay.types import BaseModel
from clay.utils.unions import parse_open_union
from functools import partial
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


NextQueryModeResultsResponseTypedDict = TypeAliasType(
    "NextQueryModeResultsResponseTypedDict",
    Union[
        NextQueryModePeopleResultsResponseTypedDict,
        NextQueryModeCompanyResultsResponseTypedDict,
    ],
)


class UnknownNextQueryModeResultsResponse(BaseModel):
    r"""A NextQueryModeResultsResponse variant the SDK doesn't recognize. Preserves the raw payload."""

    source_type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_NEXT_QUERY_MODE_RESULTS_RESPONSE_VARIANTS: dict[str, Any] = {
    "people": NextQueryModePeopleResultsResponse,
    "companies": NextQueryModeCompanyResultsResponse,
}


NextQueryModeResultsResponse = Annotated[
    Union[
        NextQueryModePeopleResultsResponse,
        NextQueryModeCompanyResultsResponse,
        UnknownNextQueryModeResultsResponse,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="source_type",
            variants=_NEXT_QUERY_MODE_RESULTS_RESPONSE_VARIANTS,
            unknown_cls=UnknownNextQueryModeResultsResponse,
            union_name="NextQueryModeResultsResponse",
        )
    ),
]
