"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .publicapimatchedexperience import (
    PublicAPIMatchedExperience,
    PublicAPIMatchedExperienceTypedDict,
)
from clay.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class LocationTypedDict(TypedDict):
    city: Nullable[str]
    name: Nullable[str]
    state_or_province: Nullable[str]


class Location(BaseModel):
    city: Nullable[str]

    name: Nullable[str]

    state_or_province: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class PublicAPIPersonSearchResultTypedDict(TypedDict):
    clay_profile_id: float
    first_name: Nullable[str]
    last_name: Nullable[str]
    location: LocationTypedDict
    matched_experiences: List[PublicAPIMatchedExperienceTypedDict]
    name: Nullable[str]


class PublicAPIPersonSearchResult(BaseModel):
    clay_profile_id: float

    first_name: Nullable[str]

    last_name: Nullable[str]

    location: Location

    matched_experiences: List[PublicAPIMatchedExperience]

    name: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
