"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class PublicAPICompanySearchResultTypedDict(TypedDict):
    annual_revenue: Nullable[str]
    clay_company_id: float
    country: Nullable[str]
    description: Nullable[str]
    domain: Nullable[str]
    industry: Nullable[str]
    linkedin_url: Nullable[str]
    location: Nullable[str]
    name: Nullable[str]
    size: Nullable[str]
    total_funding_amount_range_usd: Nullable[float]
    type: Nullable[str]


class PublicAPICompanySearchResult(BaseModel):
    annual_revenue: Nullable[str]

    clay_company_id: float

    country: Nullable[str]

    description: Nullable[str]

    domain: Nullable[str]

    industry: Nullable[str]

    linkedin_url: Nullable[str]

    location: Nullable[str]

    name: Nullable[str]

    size: Nullable[str]

    total_funding_amount_range_usd: Nullable[float]

    type: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
