"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class PublicAPIMatchedExperienceTypedDict(TypedDict):
    company: Nullable[str]
    end_date: Nullable[str]
    location: Nullable[str]
    start_date: Nullable[str]
    title: Nullable[str]


class PublicAPIMatchedExperience(BaseModel):
    company: Nullable[str]

    end_date: Nullable[str]

    location: Nullable[str]

    start_date: Nullable[str]

    title: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
