"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from typing_extensions import TypedDict


class QueryModeReferenceResponseTypedDict(TypedDict):
    r"""200"""

    reference: str


class QueryModeReferenceResponse(BaseModel):
    r"""200"""

    reference: str
