"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cellresult import CellResult, CellResultTypedDict
from .fieldmeta import FieldMeta, FieldMetaTypedDict
from clay.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class QueryResponseTypedDict(TypedDict):
    data: List[Dict[str, CellResultTypedDict]]
    cursor: NotRequired[str]
    fields: NotRequired[Dict[str, FieldMetaTypedDict]]


class QueryResponse(BaseModel):
    data: List[Dict[str, CellResult]]

    cursor: Optional[str] = None

    fields: Optional[Dict[str, FieldMeta]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cursor", "fields"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
