"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from clay.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class RunRoutineBatchUploadURLRequestTypedDict(TypedDict):
    routine_id: str


class RunRoutineBatchUploadURLRequest(BaseModel):
    routine_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
