"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Any, Dict, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


class ErrorTypedDict(TypedDict):
    message: str


class Error(BaseModel):
    message: str


RunResultItemStatus = Union[
    Literal[
        "complete",
        "failed",
    ],
    UnrecognizedStr,
]


class RunResultItemTypedDict(TypedDict):
    id: str
    status: RunResultItemStatus
    error: NotRequired[ErrorTypedDict]
    result: NotRequired[Dict[str, Any]]


class RunResultItem(BaseModel):
    id: str

    status: RunResultItemStatus

    error: Optional[Error] = None

    result: Optional[Dict[str, Any]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error", "result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
