"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class ItemTypedDict(TypedDict):
    id: str
    inputs: Dict[str, Any]


class Item(BaseModel):
    id: str

    inputs: Dict[str, Any]


class RunRoutineRequestTypedDict(TypedDict):
    items: List[ItemTypedDict]
    webhook_id: NotRequired[str]
    r"""ID of a registered Clay webhook to notify when the run finishes."""


class RunRoutineRequest(BaseModel):
    items: List[Item]

    webhook_id: Optional[str] = None
    r"""ID of a registered Clay webhook to notify when the run finishes."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["webhook_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
