"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .runroutinerequest import RunRoutineRequest, RunRoutineRequestTypedDict
from clay.types import BaseModel
from clay.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class RunRoutineRequestRequestTypedDict(TypedDict):
    routine_id: str
    body: RunRoutineRequestTypedDict
    r"""Body"""


class RunRoutineRequestRequest(BaseModel):
    routine_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        RunRoutineRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Body"""
