"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel
from clay.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class RunRoutineResponseTypedDict(TypedDict):
    routine_run_id: str
    status: Literal["in_progress"]


class RunRoutineResponse(BaseModel):
    routine_run_id: str

    status: Annotated[
        Annotated[
            Literal["in_progress"], AfterValidator(validate_const("in_progress"))
        ],
        pydantic.Field(alias="status"),
    ] = "in_progress"


try:
    RunRoutineResponse.model_rebuild()
except NameError:
    pass
