"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .runresultitem import RunResultItem, RunResultItemTypedDict
from clay.types import BaseModel, UNSET_SENTINEL
from clay.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunResultsCompleteTypedDict(TypedDict):
    data: List[RunResultItemTypedDict]
    finished: float
    routine_run_id: str
    total: float
    cursor: NotRequired[str]
    status: Literal["complete"]


class RunResultsComplete(BaseModel):
    data: List[RunResultItem]

    finished: float

    routine_run_id: str

    total: float

    cursor: Optional[str] = None

    status: Annotated[
        Annotated[Literal["complete"], AfterValidator(validate_const("complete"))],
        pydantic.Field(alias="status"),
    ] = "complete"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    RunResultsComplete.model_rebuild()
except NameError:
    pass
