"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchfieldsguidance import SearchFieldsGuidance, SearchFieldsGuidanceTypedDict
from .searchfilterfield import SearchFilterField, SearchFilterFieldTypedDict
from clay.types import BaseModel, UnrecognizedStr
from typing import List, Literal, Union
from typing_extensions import TypedDict


SearchFieldsResponseSourceType = Union[
    Literal[
        "people",
        "companies",
    ],
    UnrecognizedStr,
]


class SearchFieldsResponseTypedDict(TypedDict):
    fields: List[SearchFilterFieldTypedDict]
    guidance: SearchFieldsGuidanceTypedDict
    source_type: SearchFieldsResponseSourceType


class SearchFieldsResponse(BaseModel):
    fields: List[SearchFilterField]

    guidance: SearchFieldsGuidance

    source_type: SearchFieldsResponseSourceType
