"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.types import BaseModel, UnrecognizedStr
from typing import Any, Dict, Literal, Union
from typing_extensions import TypedDict


SearchCreateExampleSourceType = Union[
    Literal[
        "people",
        "companies",
    ],
    UnrecognizedStr,
]


class RequestTypedDict(TypedDict):
    filters: Dict[str, Any]
    source_type: SearchCreateExampleSourceType


class Request(BaseModel):
    filters: Dict[str, Any]

    source_type: SearchCreateExampleSourceType


class SearchCreateExampleTypedDict(TypedDict):
    intent: str
    request: RequestTypedDict


class SearchCreateExample(BaseModel):
    intent: str

    request: Request
