"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .startbatchrequest import StartBatchRequest, StartBatchRequestTypedDict
from clay.types import BaseModel
from clay.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class StartRoutineRunBatchRequestTypedDict(TypedDict):
    routine_id: str
    body: StartBatchRequestTypedDict
    r"""Body"""


class StartRoutineRunBatchRequest(BaseModel):
    routine_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        StartBatchRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Body"""
