"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .aggregateselect import AggregateSelect, AggregateSelectTypedDict
from .fieldselect import FieldSelect, FieldSelectTypedDict
from .filterexpression import FilterExpression, FilterExpressionTypedDict
from clay.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


FieldMode = Literal[
    "names",
    "ids",
]


class OnTypedDict(TypedDict):
    left: str
    right: str


class On(BaseModel):
    left: str

    right: str


Type = Literal[
    "inner",
    "left",
]


class JoinTypedDict(TypedDict):
    on: OnTypedDict
    table: str
    type: NotRequired[Type]


class Join(BaseModel):
    on: On

    table: str

    type: Optional[Type] = "inner"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


Direction = Literal[
    "asc",
    "desc",
]


class OrderByTypedDict(TypedDict):
    field: str
    direction: NotRequired[Direction]


class OrderBy(BaseModel):
    field: str

    direction: Optional[Direction] = "asc"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["direction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SelectTypedDict = TypeAliasType(
    "SelectTypedDict", Union[AggregateSelectTypedDict, FieldSelectTypedDict]
)


Select = TypeAliasType("Select", Union[AggregateSelect, FieldSelect])


class TableTypedDict(TypedDict):
    id: str
    alias: NotRequired[str]


class Table(BaseModel):
    id: str

    alias: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alias"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StructuredQueryTypedDict(TypedDict):
    tables: List[TableTypedDict]
    field_mode: NotRequired[FieldMode]
    filter_: NotRequired[FilterExpressionTypedDict]
    group_by: NotRequired[List[str]]
    join: NotRequired[List[JoinTypedDict]]
    order_by: NotRequired[List[OrderByTypedDict]]
    select: NotRequired[List[SelectTypedDict]]


class StructuredQuery(BaseModel):
    tables: List[Table]

    field_mode: Optional[FieldMode] = None

    filter_: Annotated[Optional[FilterExpression], pydantic.Field(alias="filter")] = (
        None
    )

    group_by: Optional[List[str]] = None

    join: Optional[List[Join]] = None

    order_by: Optional[List[OrderBy]] = None

    select: Optional[List[Select]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["field_mode", "filter", "group_by", "join", "order_by", "select"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    StructuredQuery.model_rebuild()
except NameError:
    pass
