"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clay.errors import ClayError
from clay.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class ErrorResponseData(BaseModel):
    message: str


@dataclass(unsafe_hash=True)
class ErrorResponse(ClayError):
    data: ErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: ErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
