"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "gtm-clay"
__version__: str = "0.0.1"
__openapi_doc_version__: str = "0"
__gen_version__: str = "2.916.4"
__user_agent__: str = "speakeasy-sdk/python 0.0.1 2.916.4 0 gtm-clay"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
